### ISSUE TITLE
mh1983 here

### ISSUE THREAD

**Issue by mholl1983** [AlexeyGurevsky/SleepNoise#1]
Hi, I left CrackBerry Forums for personal reasons but just wanted to say thank you for the great development effort on our dying BB platforms! Happy to continue to support your offerings and will keep an eye out. :) Thanks and take care!

**Comment by mholl1983** [comment]
is there any way to private message you for updates? Thanks!

**Comment by AlexeyGurevsky** [comment]
@mholl1983 Hi Mark, you can text me at alexey.gurevskiy@gmail.com
